language: python
python:
  - "3.6"

install:
  - pip install .
  - pip install -r requirements.txt

script:
  - python tst/model-test.py

#services:
#  - docker
#
#before_install:
#  - docker pull tensorflow/tensorflow
#  - docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow
#  - docker ps -a

